config/routes.rb
Rails.application.routes.draw do

  
root 'pages#home'
  
get 'about', to: 'pages#about'

resources :articles

end

app/models/concerns/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 2, maximum: 50 }
  validates :description, presence: true, length: { minimum: 5, maximum: 300 }
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article was successfully created."
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def show
  end
  
  def index
    @articles = Article.all
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def edit
  end
  
  def destroy
    
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end
  
  private
    def set_article
      @article = Article.find(params[:id])
    end
    
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    
  end
  
  def about
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class='row'>
  <div class='col-xs-12'>
    </div>
    <%= form_for(@article, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
        <div class='form-group'>
          <div class='control-label col-sm-2'>
            <%= f.label :title %>
          </div>
          <div class='col-sm-8'>
            <%= f.text_field :title, class: 'form-control', placeholder: 'Name of Character', autofocus: true %>
          </div>
        </div>
        <div class='form-group'>
          <div class='control-label col-sm-2'>
            <%= f.label :description %>
          </div>
          <div class='col-sm-8'>
            <%= f.text_area :description, rows:5, class: 'form-control', placeholder: 'Character Description', autofocus: true %>
          </div>
        </div>
        <div class='form-group'>
          <div class='col-sm-offset-2 col-sm-10'>
            <%= f.submit class: 'btn btn-primary btn-lrg'%>
          </div>
        </div>
    <% end %>

    <div class='center'>
      <%= link_to "Cancel Changes and Return to All Characters", articles_path %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align='center'> Edit Existing Character </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing All Characters</h1>

<% @articles.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
        </div>
        <div class="article-actions">
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete", article_path(article), method: :delete, 
                          data: {confirm: "Are you sure you want to delete this character?"}, 
                          class: "btn btn-xs btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1 align='center'>Add a Character</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Character: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <div class="description2"><%= simple_format(@article.description) %></div>
  <div class="article-actions">
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete", article_path(@article), method: :delete, 
                          data: {confirm: "Are you sure you want to delete this character?"}, 
                          class: "btn btn-xs btn-danger" %>
    <%= link_to "Back", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="http://www.minigameofthrones.com"> Minigame of Thrones</a>
      by <a href= "https://www.linkedin.com/in/johnmwujciak/">John Wujciak</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
        <!-- Add more pages on site here to create sitemap -->
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <%end%>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" id="logo" href="#">Minigame of Thrones</a>*/ -->
      <%= link_to "Minigame of Thrones", root_path, class: "navbar-brand strokeme", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Rules", about_path %></li>
        <li><a href="#">Get Started</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Characters <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Characters", articles_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Starks</a></li>
            <li><a href="#">Lannisters</a></li>
            <li><a href="#">Targaryens</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Unaligned</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Beasts of the Realm</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1> About this App </h1>

<div><%= image_tag 'Hodor.gif' %></div>
<div><%= link_to "Home", root_path %></div>

app/views/pages/home.html.erb
<div class="center jumbotron strokeme">
  <h1>Coming This Season.</h1>
  <br></br>
  <!-- <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p> -->
  <p><%= link_to "Login", "#", class: "btn btn-primary btn-lg btn-xlg" %></p>
  <p><%= link_to "Create Login", "#", class: "btn btn-primary btn-lg btn-xlg" %></p>
  <!-- <%= image_tag 'JonandGhost.gif' %> -->
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        </div>
      </div>
    </div>
  </div>
<% end %>